### ISSUE TITLE
Unable to append inline javascripts in page when the page using marko5

### ISSUE THREAD

**Issue by baburammy** [marko-js/marko#154] opened 2015-10-12 22:48 UTC
The below line is not working in marko5 and I have tested the `$(document).append()` in some other pages and It is working fine . I think Marko interrupt this append method. Kindly let me know If you have any idea about this issue.

Testing append method:-

```javascript
$(document).append($('<script>alert("")</script>'));
```

In js code:-

```javascript
$(document).append($(response.inlineJs));
```

**Comment by patrick-steele-idem** [comment] 2015-10-12 23:10
Is that code being included inside an inline `<script>` block that inside a Marko template?

**Comment by baburammy** [comment] 2015-10-12 23:29
The below function loads the inline js in the page and it is wrapped with <script> tag.
loadInlineJs: function(response) {
        if (response && response.inlineJs) {
            $(document).append($(response.inlineJs));
        }
    },
eg:-
<script>(function(){})();</script>
It was working fine with marko4 and It is not working with marko5.

**Comment by baburammy** [comment] 2015-10-13 19:21
![image](https://cloud.githubusercontent.com/assets/286382/10465666/e5b2df4e-71a4-11e5-8b5a-680a647ca947.png)

**Comment by patrick-steele-idem** [comment] 2015-10-13 19:26
Hi @baburammy, I am having a hard time understanding the issue and how it relates to Marko Widgets based on the details provided. It looks to me that the issue is completely unrelated to Marko and Marko Widgets, but I could be missing something.

With that said, I would not be using jQuery to execute the inline JS. It is better to send down the inline JS without the surrounding `<script>` tag. Instead, just send down the raw JS code and use `eval(response.inlineJs)` to run the inline code.

If you have a sample project or more code that you can share that would make it easier for me to provide help.

**Comment by patrick-steele-idem** [comment] 2015-12-07 21:33
Hey @baburammy, I'm just going through issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. Thanks.

**Closed by patrick-steele-idem** 2015-12-07 21:33 UTC
