### ISSUE TITLE
handle ES module components

### ISSUE THREAD

**Issue by christopherjbaker** [marko-js/marko#850] opened 2017-09-18 04:43 UTC
### Description
Allow component.js files to be created via ES modules (`export default class {}`).

### Context
I prefer to use `import`/`export` with babel instead of `require`/`module.exports`

### Possible Implementation
The imported object from an es export like `export default class {}` is `{ default: class {} }`. Just need to look for the "default" key if the main object doesn't fit the expected structure.

### Is this something you're interested in working on?
Yes. I attempted to do this myself, though I could not find the correct place to add the logic.

**Comment by mlrawlings** [comment] 2017-09-19 18:13
@christopherjbaker Thanks for bringing this up!  We definitely want to support this (especially since ES modules are now behind a flag in Node 8.5).

The question is what do we want this to look like.  

- We could do what the latest node does: treat `component.mjs` as ESM and `component.js` as CJS.
- We could do something similar to babel (and what we already do for `import` within templates): `component = component.default || component`.  This is more compatible with how most people have been using ESM (without `.mjs`) but also runs the risk of a CJS module exporting an object with a `default` property being interpreted as ESM.

Babel actually adds an additional check for `__esModule` which is added to the exports of a module:
```js
export let foo = 123;
export default 456;
```
```js
exports.__esModule = true;
var foo = exports.foo = 123;
exports.default = 456;
```
But this is not a standard behavior.

**Comment by mlrawlings** [comment] 2017-09-19 21:31
Putting this here as note:

Attempting to `require` an ESM from CJS will throw an error in Node 8.5:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
```

This means if we want to support `component.mjs` the template will need to compile to ESM.

**Comment by jasonmacdonald** [comment] 2017-09-25 11:25
Just as a note, you can already do this today with Babel, you just need to include the Babel plugin `babel-plugin-add-module-exports` which will add the standard `module.exports` to the exported modules in your compiled output. FYI.

**Comment by DylanPiercey** [comment] 2018-08-29 03:45
Already closed a duplicate of this ([see here](https://github.com/marko-js/marko/issues/953)). Ultimately we are currently planning to address this by migrating our compiler to use babel under the hood in `marko-js/x` (very WIP atm) and it will not likely get added to the v4 codebase.

**Closed by DylanPiercey** 2018-08-29 03:45 UTC
Labels: type:feature
