### ISSUE TITLE
Problems with destructured imports in .marko file using webpack.

### ISSUE THREAD

**Issue by hedefalk** [marko-js/marko#1157] opened 2018-10-25 11:12 UTC
### Details

I have used destructured imports in the top of Marko files a lot before, but this time something is wrong.

I have a top destructured import like:

`import {foo, bar} from 'app/utils'`

which I then use in the template.

`<a href=foo.generateUrl()>`

### Expected Behavior
I expected that foo and bar would be resolved and defined at the point of render.

### Actual Behavior
foo and bar are both undefined when render is called.

### Possible Fix
Just changing this to a non-destructured import with later dereferencing works fine.

`import utils from 'app/utils'
…
<a href=utils.foo.generateUrl()>`

<details><summary>Additional Info</summary>

### Output bundle

The output code looks something like this:

```
module_utils_module = __webpack_require__(40),
utils_module = module_utils_module.default || module_utils_module,
foo = module_utils_module.createRestricted,
bar = module_utils_module.createAttestation,

At the point where I hit this definition `module_utils_module` is defined to an object with all it's properties undefined and no default. In this example `module_utils_module` is

{foo: undefined, bar: undefined, __esModule: true} when using Chrome dev tools.

```

### Your Environment
webpack: 3.11.0
marko-loader: 1.3.2

### Steps to Reproduce
I'm gonna have to work a bit to get something minimal I can show. I've used a lot of destructuring imports before that worked fine so seems like some kind if special case going on, some kind of race condition I guess.

</details>

**Comment by hedefalk** [comment] 2018-11-18 09:49
I'll try to fix up a repo. I haven't been able to fix it other than using normal imports. I've struck it a few times though.

**Comment by hedefalk** [comment] 2018-11-19 07:09
Yeah, it seems this special case is some kind of circular dependency. Having trouble with repro. It works fine with non-destructured imports though so maybe that's a heads up…

**Comment by DylanPiercey** [comment] 2018-11-19 15:21
When you don’t destructure you get a reference to the exports object (which can then be updated by the module you import). This means that as long as you don’t access the helper function immediately (and you aren’t completely overwriting the exports like `module.exports = newthing`) then the you will have access to the exports by the time you render.

You can double check this by not using destructured exports and logging both immediately and when you render like so:

```marko
import utils from “app/utils”;

static console.log(utils.foo); // undefined

$ console.log(utils.foo); // not undefined
```

**Comment by DylanPiercey** [comment] 2018-11-26 19:42
Closing this for now, feel free to ping me if you discover something Marko related is the cause.

**Closed by DylanPiercey** 2018-11-26 19:42 UTC
