### ISSUE TITLE
npm not installing dependencies (node 0.12.9, npm 3.5.1)

### ISSUE THREAD

**Issue by patbegg** [marko-js/marko#168] opened 2015-12-07 03:46 UTC
Hi,
Just to let you know there seems to be a problem with npm installing dependencies for the 'marko' package (in particular I noticed marko-layout wasn't being installed). I made sure 'marko-layout' wasn't installed in the main projects package.json file. Tries a clean uninstall of all npm packages, npm cache clean, and then install and still no joy. I think it is linked to the version on npm.
I managed to resolve this by 'cd' into node_modules/marko and running npm install there.

Hope it helps someone.

**Comment by patrick-steele-idem** [comment] 2015-12-07 16:24
Hey @patbegg, thanks for reporting the problem. I'll take a look into it. What version of npm are you using?

**Comment by patrick-steele-idem** [comment] 2015-12-07 16:40
Hey @patbegg, are you sure `marko-layout` is not being installed? I wasn't able to reproduce the problem with the latest npm version (v3.5.1). I suspect that you are using the latest version of `npm` (^3.5.1) and the latest version of `npm` flattens all of the installed `node_modules`. If that is the case then you should find `marko-layout` as a child of your top-level `node_modules` directory. 

If you were using an older version of `npm` and then later switched to a new version of `npm` then I suggest forcing a recompile of all your templates since the directory structure may have changed and the compiler might need to recalculate relative paths that get generated. You can force a recompile using either of the following approaches:

Option 1) Force a recompile of templates by setting the `MARKO_CLEAN` environment variable to `true` (recommended):

```
MARKO_CLEAN=true node index.js
```

Option 2) Use the `markoc` command line utility to delete the generated `*.marko.js` files:

```
markoc . --clean
```

Please let me know if that solves your problem. Thanks.

**Comment by patbegg** [comment] 2015-12-08 03:42
Thanks this solved it. Was pulling my hair out. Would be good to get this in the marko docs, maybe in a section about moving an app to production. 
What I actually did was stop grunt from copying the 'template.marko.js' files to the build so they were generated again on the server. Is that a suitable way of doing it?

**Comment by patrick-steele-idem** [comment] 2015-12-08 04:46
Hey @patbegg, glad that solved your problem.

If you know the directory structure is exactly the same on both machines then it is okay to copy over the compiled templates. If there is any chance that the directory structure will be different then I would just not copy the compiled templates and, instead, have them be lazily compiled on the target machine as you did.

How about we open another issue to track the docs improvement? I'm going to go ahead and close this issue for now.

**Closed by patrick-steele-idem** 2015-12-08 04:46 UTC
Labels: community-contribution
