### ISSUE TITLE
Event Handlers Not Attached For Imported Marko Tags

### ISSUE THREAD

**Issue by makinde** [marko-js/marko#1169] opened 2018-11-17 05:40 UTC
### Details

I'm writing a taglib for spectre.css ([`marko-spectre`](http://github.com/makinde/marko-spectre). The one tag that I've implemented has a click handler on an element. When I use the <TabItem/> element on a page that has no other dom listeners, the click handlers are not fired. When I add another click event anywhere else on the page, the `<TabItem>` components click handlers start getting fired.

### Expected Behavior

Imported component click handlers should always be called

### Actual Behavior

Imported component click handlers are only called when the parent page already has a click handler

### Your Environment

- Safari 12.0, Node 10.4
- Mac OS 10.14
- Link to your project: http://github.com/makinde/marko-spectre

### Steps to Reproduce

Create a new marko project. `npm i marko-spectre`. Include a `<TabItem>` onto the page. observe that no click handler is fired when the tab is clicked on. Here's some sample code to use in your app.

```
      <Tab block=true>
        <TabItem active=true on-select('switchTab', 'login')>Log In</TabItem>
        <TabItem active=false on-select('switchTab', 'signup')>Sign Up</TabItem>
      </Tab>
```

**Comment by DylanPiercey** [comment] 2018-11-18 03:12
@makinde I've done what you mentioned in the "Steps to Reproduce" section and have created a bare bones repo. It appears to be working for me in both Marko 4.13.5 (the version you mentioned) and 4.13.10 (latest).

Here is my repo: https://github.com/DylanPiercey/marko-issue-1169

Are you able to put up your own repo where this is broken and we can find out why?

**Comment by makinde** [comment] 2018-11-20 01:02
Thanks for looking into this. I now realize that I was doing something that may have broken this in a subtler way.

I'm often developing small modules to use in my larger project. For speed of iteration, I'll sometimes install those smaller modules directly from the filesystem. e.g. `npm i ../marko-spectre`. When I do this, I often get a cryptic error about an `id` attribute expecting a string and getting an object. Note, this error goes away if I install the module from npm (`npm i marko-spectre`)...even when the code on the repo and on my local file system is the same.

I discovered that this error goes away when I run `npm i marko --no-save` from within the `marko-spectre` directory. I now suspect that the separate install of marko is somehow cause multiple event systems to be on the page (or something like that).

Let me see if I can get you a copy of the code. There's a lot going on in there right now.

**Comment by DylanPiercey** [comment] 2018-12-06 21:01
Since it sounds like the issue is related to the way things are installed and not exactly the labeled issue I think it makes sense to close this for now. Feel free to leave a comment and we can reopen if necessary, or a new issue may make sense.

**Closed by DylanPiercey** 2018-12-06 21:01 UTC
Labels: needs more info, type:unverified bug
