### ISSUE TITLE
Strange Lasso error when defind a class on the main index.marko file

### ISSUE THREAD

**Issue by Gillespie59** [marko-js/marko#804] opened 2017-08-16 15:18 UTC
As described in our chat on twitter (https://twitter.com/psteeleidem/status/897118020727848960) I am a totally newbie with Marko. I have juste spent one or two hours with the framework. So maybe the problem is me. But I want to share two small problems I had (I will create another issue for the second problem)

When I add a class in my main marko file (https://github.com/Gillespie59/frameworks-web/blob/master/devfest-marko/src/index.marko) like that : 

```
class {
  
}
<site-layout>
  <@title>Marko Starter</@title>
  <@content>
    <app />
  </@content>
</site-layout>
```

I have a Lasso error. Maybe I did something wrong, but the error message should be more clear ;)

![image](https://user-images.githubusercontent.com/555768/29370847-e7d08078-82a6-11e7-9fc9-4bb6aef5e733.png)

**Comment by patrick-steele-idem** [comment] 2017-08-16 18:18
@Gillespie59 Thank you for opening this issue as well.

@mlrawlings do you mind taking a look at this issue?

**Comment by mlrawlings** [comment] 2017-08-21 19:59
@Gillespie59 That specific error is now fixed (there was a custom `lasso` tag used by `marko-starter` that was designed only to run on the server - it is now a noop in the browser).  

However, you're still going to have issues with a top level component if you do any re-rendering.  When diffing `<head>` and `<body>` any content added by server-only code (like `lasso`) or other scripts/styles added by third-party libraries (`jquery` plugins, font-loaders, browser extensions, a third-party sdk, etc.) will be removed and probably break your page.

Note, [React et al. have this same limitation](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375).

**Comment by mlrawlings** [comment] 2017-08-21 23:21
I would admit, however, that this is a larger issue for Marko since we recommend using Marko from the top down, so I can understand how it would be confusing.  Thanks for taking the time to report this.

We're looking at possibilities for making the diffing algorithm special case `<head>` and `<body>` with the understanding that Marko doesn't control everything that might be added to them.  

The other option is to treat this as an anti-pattern and warn the developer if they are doing this.

**Comment by mlrawlings** [comment] 2017-09-29 22:25
Closing as this specific issue is resolved.  #810 still needs to be addressed.  Any dicussion can continue there.

**Closed by mlrawlings** 2017-09-29 22:25 UTC
Labels: type:bug
