### ISSUE TITLE
[v4] Strange nested component redraw bug after updating parent state

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#546] opened 2017-01-24 02:55 UTC
### Context

Take a page containing the following...

```html
<h1>Hello!</h1>
<session-panel />
```

...with a `session-panel` component defined in a singe `index.marko` file...

<details>
<summary>components/session-panel/index.marko</summary>

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { passwordGrade: 'bad' }
  },
  setGrade(newGrade) {
    console.log("Setting", newGrade)
    this.state.passwordGrade = newGrade
  }
}
</script>

<form class="session-panel" method="POST">

  <h3>Sign Up for an Account:</h3>
  <password-picker on-grade('setGrade') />
  <button type="submit" disabled=( state.passwordGrade == 'bad' )>Sign Up</button>

</form>
```

</details>

...and the following component for `password-picker`...

<details>
<summary>components/password-picker/index.marko</summary>

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { password: '', grade: 'bad' }
  },
  setPassword(e) {
    this.state.password = e.target.value
    if (this.state.password.length >= 3) {
      this.state.grade = 'good' // joke
    }
    else {
      this.state.grade = 'bad'
    }
    console.log("Emitting", this.state.grade)
    this.emit('grade', this.state.grade)
  },
}
</script>

<div class="password-picker">

  <input type="password" name="password" value=state.password
         on-input('setPassword') placeholder="Please enter a password" />

  <div class="grade">
    Password strength:
    <b if(state.grade == 'good')>Good!</b>
    <b else>Bad password. Bad!</b>
  </div>
</div>
```

</details>

### Expected Behavior

Typing three characters into the input box should enable the submit button.

### Actual Behavior

Typing three characters into the input box resets and re-initializes the `password-picker` component. Typing another character also does not show up. It does enable the submit button, though.

If you remove the `this.state.passwordGrade = newGrade` line, the `password-picker` component no longer re-initializes.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: v4.0.0-rc.8
* Environment name and version: Chrome 54
* Operating System and version: OS X
</details>

**Comment by patrick-steele-idem** [comment] 2017-01-24 03:36
This is not a bug in marko and marko is behaving as expected. Your `password-picker` component is stateful and every time it receives new input it is resetting its state to `{ password: '', grade: 'bad' }`. The problem is that the `password-picker` component is emitting an event that causes its parent component to rerender. When the parent UI component rerenders it is rerendering the child `password-picker` with new input (i.e., `<password-picker on-grade('setGrade') />`).

You can use the `no-update` attribute to prevent the child `password-picker` from rerendering when its parent UI component rerenders:

```xml
<password-picker on-grade('setGrade') no-update />
```

That seems to solve the problem for me. Does that work for you? I'm closing the issue, but please feel free to open if you still have concerns.

**Closed by patrick-steele-idem** 2017-01-24 03:36 UTC

**Comment by mindeavor** [comment] 2017-01-24 03:56
ooh, I see! I misunderstood marko's component lifecycle. For the record, am I misusing `onInput` to set initial state?  Is there a more appropriate lifecycle method I should be using?

**Comment by mindeavor** [comment] 2017-01-24 04:05
Oh yeah: adding `no-update` worked, but that doesn't seem like a good genenal solution, since it doesn't allow the component to accept future changes from its parent.

A more general solution would be to only set state if it does not exist:

```js
  onInput(attrs) {
    if ( ! this.state ) {
      this.state = { password: '', grade: 'bad' }
    }
  },
```

that way the component can decide to take potentially-changing input from `attrs` if it needs to.

**Comment by mlrawlings** [comment] 2017-01-26 18:31
@mindeavor I wonder if there could be value in making use of the `constructor`:

```js
class {
    constructor(input, out) {
        this.state = {
            count: input.startCount
        };
    }
    onInput(input, out) {
        this.state.color = input.color;
    }
    increment() {
        this.state.count++;
    }
}

<div>${state.count}</div>
<button on-click('increment')>+</button>
```

```xml
<counter start-count=0 color="#ccc"/>
```

In this example, _both_ `constructor` and `onInput` would be called when creating the component,
yielding an initial state of `{ count:0, color:'#ccc' }`.

Changing the value of the `color` attribute would only call `onInput` and therefore would not clobber the existing `count`.

**Comment by mindeavor** [comment] 2017-01-26 18:59
@mlrawlings Yes, using `constructor` makes a lot of sense :) How would `constructor` run with respect to server/client side rendering?
