### ISSUE TITLE
Hot reload doesnt work in ExpressJS

### ISSUE THREAD

**Issue by sriver111** [marko-js/marko#383] opened 2016-10-22 21:42 UTC
## Bug Report
Hot reload doesnt work in ExpressJS setup

### Your Environment
Win8.1 
Chrome

**Comment by patrick-steele-idem** [comment] 2016-10-22 23:19
Hey @sriver111, we'll need more details to help you out. Have you tried using [browser-refresh](https://github.com/patrick-steele-idem/browser-refresh) to enable hot reloading of templates? Here's a sample app that demonstrates hot reloading that I recommend checking out: https://github.com/marko-js-samples/marko-hot-reload

**Comment by sriver111** [comment] 2016-10-25 06:42
Hi, the browser refresh only refreshes the browser page load.
I did manual refresh, and it doesnt work.
The file watch does work and the method handleFileModified(templatePath) is triggered, but nothing happens, even though there is console printout from 'require' module that say ' file refreshed...' (or something). Also, the compiler doesnt output new js file either, even after setting write to file option as true.

**Comment by basickarl** [comment] 2016-10-25 13:47
@sriver111 I happened to have this error 5 minutes ago, the console printout, is it the relative path or the absolute path. It needs to be the absolute path i.e. `/home/user/dev/yourproject/src/markofiles/component/app-mycomponent/template.marko`

**Comment by patrick-steele-idem** [comment] 2016-10-25 15:58
@sriver111 would it be possible to share a minimal project to reproduce the problem? I'm not able to reproduce, but it is possible that a Windows-specific issue has creeped in.

FYI, hot reloading works in the following way:

When hot reloading is enabled, the `Template` class is monkey-patched to proxy all of the rendering methods in order to check if the template needs to be reloaded or not before calling the original method. In addition, when a `.marko` file is modified it is deleted from the `require.cache` so that it can be reloaded through the Node.js module loading system. I can share more information, but just wanted to give you an idea how it works.

**Comment by sriver111** [comment] 2016-10-29 16:57
Hi Patrick, u are right. The path has to be absolute to work.
Thanks and cheers!

**Comment by patrick-steele-idem** [comment] 2016-10-30 15:13
Glad you got it working. Closing the issue. Thanks for the update.

**Closed by patrick-steele-idem** 2016-10-30 15:13 UTC
Labels: status:needs-clarifying
