### ISSUE TITLE
Isomorphically rendered components cannot get the correct state.

### ISSUE THREAD

**Issue by ulivz** [marko-js/marko#1085] opened 2018-07-14 07:09 UTC
### Details

Recently we upgrade `marko.js` from `4.7` to `4.12`, but our code doesn't work since then.

We all used isomorphically rendered UI component, so the component will be rendered at server, although the data returned to client is same to before, but due to this commit (https://github.com/marko-js/marko/pull/1010/commits/66b43e33c267029996539e48ca0e198c909fd1f6):

https://github.com/marko-js/marko/blob/b5f5f669ae2aff81868eafb8c46d466b61b6a6d3/src/components/ComponentDef.js#L130-L140

Since the input was an empty object, so it will cause the client cannot initialize the correct state.

### Expected Behavior

Client should get the correct initial state.

### Actual Behavior

Client cannot get the correct initial state.

### Possible Fix

I cannot commented these following code, all work for me.

``` js
 if (flags & FLAG_WILL_RERENDER_IN_BROWSER) { 
     if (component.onCreate) { 
         component.onCreate(input, { global: global }); 
     } 
     if (component.onInput) { 
         input = component.onInput(input, { global: global }) || input; 
     } 
 } else { 
   // Only remain this branch.
}
```

But I am sure it isn't the fix we want. and sorry I don't have too much time to continue.

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 6.11.3
- Operating System and version (desktop or mobile): all side.
- Link to your project: eBay's private project, sorry.

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by mlrawlings** [comment] 2018-07-14 18:00
> Link to your project: eBay's private project, sorry.

@ulivz can you ping me on slack?  My userid is `mirawlings`

**Comment by mlrawlings** [comment] 2018-07-20 06:45
I think this is a duplicate of #1043 (see there for more context).  You can add the following tag to your component to get the old behavior:
```marko
<marko no-browser-rerender />
```

**Closed by mlrawlings** 2018-07-20 06:45 UTC

**Comment by ianvonholt** [comment] 2018-08-14 01:49
@mlrawlings This is problematic. When you start to serialize any sort of sensitive data within the input stream on the server, any references to input specific data with onCreate is then not available in the browser.

The only work around to this is creating a split component file on any components that you only want the onCreate to run server side only.

Example: 
```
class {
   onCreate (input) {
      this.state = {
        firstName: input.user.firstName,
        lastName: input.user.lastName
      }
  }

  onInput (input) {
    // This would cause the browser to throw an error in onCreate, but not the server.
    return {}
  }
}

<header>
    <h1>Hello ${state.firstName} ${state.lastName}</h1>
</header>
```
