### ISSUE TITLE
Not compiled "Col" custom tag.

### ISSUE THREAD

**Issue by slavik-m** [marko-js/marko#1000] opened 2018-02-26 17:37 UTC
### Details

Not compiled `Col` custom tag.

### Expected Behavior

`Error(s) in template:
[src/routes/test/index.marko:24:18] The closing "Col" tag does not match the corresponding opening "row" tag`
![image](https://user-images.githubusercontent.com/12348485/36693739-e77483d6-1b44-11e8-9ed1-d773804e03e8.png)

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version: **node.js 9.4**
* Operating System and version: **macOS High Sierra 10.13.2**
* IDE:  **WebStorm 2017.2.2**

### Stack Trace

```
Error: An error occurred while trying to compile template at path ".../src/routes/test/index.marko". Error(s) in template:
1) [src/routes/test/index.marko:24:18] The closing "Col" tag does not match the corresponding opening "row" tag

    at handleErrors (.../node_modules/marko/src/compiler/Compiler.js:82:21)
    at Compiler.compile (.../node_modules/marko/src/compiler/Compiler.js:155:9)
    at _compile (.../node_modules/marko/src/compiler/index.js:99:33)
    at Object.compile (.../node_modules/marko/src/compiler/index.js:113:12)
    at compile (.../node_modules/marko/src/node-require/index.js:52:38)
    at Object.markoRequireExtension [as .marko] (.../node_modules/marko/src/node-require/index.js:120:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
```

**P.S:** Sorry for my english :)
</details>

**Comment by jasonmacdonald** [comment] 2018-02-26 18:19
Seems strange. Marko doesn't even have highlighting for Webstorm, so if the Webstorm syntax highlighter is running into problems, there might be something else going on. A strange invisible character in there? File encoding problem maybe?

**Comment by slavik-m** [comment] 2018-02-26 18:47
@jasonmacdonald
I use [Marko.tmbundle](https://github.com/marko-js/marko-tmbundle) for highlighting in my WebStorm.
Encoding UTF-8. All characters is correct (i used copy-paste).
Anything else names such as: `<cols></cols>`, `<assa></assa>` works correctly!

**Comment by jasonmacdonald** [comment] 2018-02-26 19:26
Hmm, interesting. I knew about the TM bundle, but I don't use it as you lose all the Webstorm highlighting/formatting for HTML :(

**Comment by slavik-m** [comment] 2018-02-26 20:21
Oh, I am sorry. I didn't know about [HTML `<col>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col)

I created my own custom `col` tag.
![image](https://user-images.githubusercontent.com/12348485/36692657-59e82c14-1b41-11e8-8065-4a993349ced5.png)

Can I redefine native HTML tag on my custom tag??

**Idea:**
I want to write wrapper under bootstrap. For example:
```
<row>
  <col></col>
  <col></col>
</row>
```
It seems much better than:
```
<div.row>
  <div.col></div>
  <div.col></div>
</div>
```

**Comment by slavik-m** [comment] 2018-02-26 20:46
The capital letter corrects highlighting, but error the same.
![image](https://user-images.githubusercontent.com/12348485/36693739-e77483d6-1b44-11e8-9ed1-d773804e03e8.png)

```
Error(s) in template:
1) [src/routes/test/index.marko:22:17] The closing "Col" tag does not match the corresponding opening "row" tag
```
Compiler does not case sensitive?

**Comment by jasonmacdonald** [comment] 2018-02-26 21:31
It does seem to be something specific to the name `col`. Oddly other tags don't have the issue, so I'm not 100% sure of the cause. Hopefully, someone from the team can have a look a little deeper at the issue.

**Comment by DylanPiercey** [comment] 2018-07-20 16:31
Marko currently has special handling of known HTML tag names which is why `col` is not being passed through. You can take a look at all of the handled html tag names [here](https://github.com/marko-js/marko/blob/master/src/taglibs/html/marko.json).

I would say that this happening for `col` isn't a bug, but maybe we could handle `Col` differently?

**Comment by DylanPiercey** [comment] 2018-08-29 03:09
Closing this as we are tracking PascalCase [here](
https://github.com/marko-js/marko/issues/891).

**Closed by DylanPiercey** 2018-08-29 03:09 UTC
Labels: help wanted, scope:compiler, type:bug
