### ISSUE TITLE
<include> tag not calling marko file's widget

### ISSUE THREAD

**Issue by sidsakhadeo** [marko-js/marko#292] opened 2016-05-11 17:54 UTC
When using <include> tag like so:
```
<include template="./deferred.marko" template-data="data" />
```

if deferred.marko has a widget bound to it in the `w-bind` attribute, the widget.js is not registered and invoked.

**Comment by patrick-steele-idem** [comment] 2016-05-11 19:31
I would not expect that to be the case. Would it be possible to set up a simple project to reproduce the problem? Or, could provide more details on your setup?

**Comment by mlrawlings** [comment] 2016-05-17 18:29
I'm adding some more detail to this, mostly so I don't forget: The issue is seen in v2, not sure if it is also an issue in v3.

The template that calls `<include template="./deferred.marko" template-data="data" />` is being rendered **client side**.  The widget **is** registered, but for the first render it does not call any of the [rendering methods](http://markojs.com/docs/marko-widgets/component-lifecycle/#rendering-methods), nor is the state properly set.  We can access the widget through `element.__widget`, and calling `setStateDirty()` does cause a re-render in which the rendering methods **are** called, but then the widget (which gets its contents from state) is empty because the state is not set from the first render.

**Comment by mlrawlings** [comment] 2016-07-15 19:42
@sidsakhadeo is this still an issue for you?

**Comment by mlrawlings** [comment] 2016-10-14 06:51
Closing this issue.  If this is still an issue in v3, feel free to reopen.

**Closed by mlrawlings** 2016-10-14 06:51 UTC
Labels: status:needs-clarifying, type:bug
