### ISSUE TITLE
DOM Exceptions and rendering issues

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1059] opened 2018-06-21 13:46 UTC
### Marko Version: x.x.x

    "marko": "4.10.0",
    "marko-loader": "1.3.3",

### Details

I have a marko powered isomorphic webapp in the works (nearing staging) and are running into some critical DOM issues that come up from time to time.  Reproducing them in a standalone project has been a difficult task, and I am yet to reproduce them all.

However I have managed to produce three different bugs, which I have bundled together in a single issue as I suspect they are related.  I can split them up if need be.

####  1: a `<html-comment>` tag is viewable on screen
 - not critical as I can just remove the html-comment tag however I think it may be related to the other bugs, or indicative that something is broken in how marko identifies components using html comment dom nodes.

#### 2: DOMException

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insertBefore (http://localhost:3001/static/bundle.js:2056:23)
    at morphChildren (http://localhost:3001/static/bundle.js:2351:25)
    at morphEl (http://localhost:3001/static/bundle.js:2813:13)
    at morphChildren (http://localhost:3001/static/bundle.js:2407:29)
    at morphEl (http://localhost:3001/static/bundle.js:2813:13)
    at morphChildren (http://localhost:3001/static/bundle.js:2407:29)
    at morphComponent (http://localhost:3001/static/bundle.js:2178:9)
    at morphChildren (http://localhost:3001/static/bundle.js:2369:44)
    at morphdom (http://localhost:3001/static/bundle.js:2822:5)
    at http://localhost:3001/static/bundle.js:6675:13
```

#### 3: Include/Transclude Bug

DOM nodes dissapear from the document when interacting with a sibling element

This may be related to a previous bug I submitted https://github.com/marko-js/marko/issues/1022 as the trigger (forceUpdate or state change) is the same however  but the effect of the bug is different

#### : 4 - Not yet able to reproduce in isolation

```
Uncaught TypeError: Cannot read property 'insertBefore' of null
    at insertBefore (index.js?8192:33)
    at morphComponent (index.js?8192:148)
    at morphChildren (index.js?8192:346)
    at morphdom (index.js?8192:799)
    at eval (Component.js?2cba:516)
    at Object.batchUpdate [as ___batchUpdate] (update-manager.js?8c0e:63)
    at Component.___rerender (Component.js?2cba:499)
    at Component.update (Component.js?2cba:452)
    at updateComponents (update-manager.js?8c0e:44)
    at updateUnbatchedComponents (update-manager.js?8c0e:16)
    at eval (nextTick-browser.js?bdf1:18)
    at wrapped (raven.js?8d3d:377)
```
From debugging it appears that in Component.js ___forEachNode :
I've ran in to various combinations of 
* this.___startNode.parentNode is null and this.___endNode.parentNode is null
* this.___startNode.parentNode is not = this.___endNode.parentNode
* this.___startNode is null
* this.___endNode is null
very strange

__
### Possible Fix

For bug (2) I have provided three demonstrations of how to change your marko code to work around the bugs

### Your Environment
```
"browser-refresh-taglib": "^1.1.0",
"express": "^4.14.0",
"marko": "^4.10.0",
"marko-loader": "^1.3.3",
"query-string": "^6.1.0",
"serve-static": "^1.11.1",
"webpack": "^2.6.1",
"webpack-dev-server": "2.9.3"

"@babel/core": "^7.0.0-beta.42",
"@babel/preset-env": "^7.0.0-beta.42",
"@babel/register": "^7.0.0-beta.42",
"babel-loader": "8.0.0-beta.2"
```

see package.json / yarn.lock at https://github.com/cameronbraid/marko-dom-issue/

### Steps to Reproduce

git clone https://github.com/cameronbraid/marko-dom-issue/
yarn
yarn devserver
yarn server
google-chrome http://localhost:8180

The follow the on screen instructions

**Comment by cameronbraid** [comment] 2018-06-21 18:13
I have found something related to the bug.. quite strange. 

with a Page.marko component which looks like this :

```
class {
}
$ {
  const hostname = out.global.req ? out.global.req.hostname : window.location.hostname
}
<!doctype html>
<html lang="en">
  <body>
    <html-comment>start of body</html-comment>
    <div no-update>
    <script  src="//${hostname}:3001/static/bundle.js"></script>
    </div>
  </body>
</html>
```

the server rendered html looks like this :

```
<!--M#s0--><!doctype html><html lang="en"><body><!--start of body--><div>
<script src="//dev.drivenow.com.au:3001/static/bundle.js"></script></div>
<script>(function(){var w=window;w.$components=(w.$components||[]).concat
({"w":[["s0",0,{},{"f":1}]],"t":["/marko-dom-issue-no-mobx$0.0.1/src/components/PartialHtmlCommentSimple.marko"]})||w.$componen
ts})()</script></body></html><!--M/s0-->
```

Then `init-components-browser.js` within `indexServerComponentBoundaries`, identifies the start marker `<!--M#s0-->` since it is the `firstChild` of the document, and puts it into `serverComponentStartNodes`, but never finds the end marker `<!--M/s0-->` since its not present in the DOM

**Comment by DylanPiercey** [comment] 2018-06-21 18:22
@cameronbraid I think this may be a duplicate of https://github.com/marko-js/marko/issues/810

Marko does not currently support full page components.

**Comment by cameronbraid** [comment] 2018-06-22 02:54
I identified that bug 1 in this demo was caused by using a full page component.  

I have refactored the demo to remove the full page component and unfortunately the 2 other bugs still remain.

Is someone able to take a look at this, as its a blocker for us

**Comment by cameronbraid** [comment] 2018-06-23 07:56
Fyi I have submitted a PR for a failing test case for the DOMException bug

https://github.com/marko-js/marko/pull/1064

**Comment by cameronbraid** [comment] 2018-06-23 09:35
FYI I have updated the PR to include a second failing test for a different exception

```
Component.js?2cba:548 Uncaught TypeError: Cannot read property 'nextSibling' of null
    at Component.___forEachNode (Component.js?2cba:548)
    at Component.___detach (Component.js?2cba:533)
    at morphChildren (index.js?8192:329)
    at morphComponent (index.js?8192:155)
    at morphChildren (index.js?8192:346)
    at morphdom (index.js?8192:799)
    at eval (Component.js?2cba:516)
    at Object.batchUpdate [as ___batchUpdate] (update-manager.js?8c0e:63)
    at Component.___rerender (Component.js?2cba:499)
    at Component.update (Component.js?2cba:452)
    at <anonymous>:1:34
```

**Closed** 2018-06-28 22:13 UTC
