### ISSUE TITLE
Spread operator is not usable in component class

### ISSUE THREAD

**Issue by ccinelli** [marko-js/marko#1281] opened 2019-03-13 01:52 UTC
### Details

```
class {
   onCreate(input){
      return {...input, a: 3}
   }
}
```

It does not work in the `class` inside a `.marko` file.

### Expected Behavior

Spread operator should work: `...`

### Actual Behavior

It complains that `...` is not expected

### Possible Fix

A workaround is to use the `lasso-babel-transform` and move the `class` in `component.js`

**Comment by dominikstoetter** [comment] 2019-09-04 11:47
this is most likely caused by a outdated runtime. rest/spread is a feature not present until node `8.6.0`.

If you target browsers that don't fully support ES2015 you want to transform then anyway.

**Comment by DylanPiercey** [comment] 2021-02-18 02:17
This is now fixed in Marko 5.

**Closed by DylanPiercey** 2021-02-18 02:17 UTC
