### ISSUE TITLE
Has anyone got tailwindcss to work with Marko?

### ISSUE THREAD

**Issue by treeder** [marko-js/marko#1713] opened 2021-07-14 20:27 UTC
If anyone knows how to do this properly, please share. Thanks!

PS. Might be a good idea to enable GitHub Discussions on this repo?

**Comment by DylanPiercey** [comment] 2021-08-02 15:36
This is a duplicate of https://github.com/marko-js/marko/issues/1584 - seems like there was some success over there.

**Closed by DylanPiercey** 2021-08-02 15:36 UTC
Labels: type:question
