### ISSUE TITLE
Regression in valueless attributes 

### ISSUE THREAD

**Issue by src-code** [marko-js/marko#1228] opened 2019-01-11 01:11 UTC
### Details

Valueless attributes (for example, the AMP attribute `<html ⚡ lang="en">`) began receiving a numeric attribute name sometime after 4.14.7.  Now the above tag is rendered as `<html 0="⚡" lang="en">` which is incorrect, and is a regression.  

### Expected Behavior

Attributes should be rendered without modification.

### Your Environment

Found on Node 8.12.x

**Comment by DylanPiercey** [comment] 2019-01-29 22:09
Hey @src-code, so far I haven't been able to reproduce this issue myself (starting from a blank slate with the example you have above). Are you able to either [add a failing test case](https://github.com/marko-js/marko/blob/master/.github/CONTRIBUTING.md#adding-a-failing-test-case) to Marko or create a sample repo that you could share with us?

**Comment by DylanPiercey** [comment] 2019-08-02 16:53
Going to close this one for now. If the issue is still persisting the latest version of Marko please recreate the issue and provide a reproducible example. If possible an example using a gist link on the try online (https://markojs.com/try-online/?gist=) is often simplest.

**Closed by DylanPiercey** 2019-08-02 16:53 UTC
Labels: needs more info, type:unverified bug
