### ISSUE TITLE
include tag not rendered in 4.7

### ISSUE THREAD

**Issue by hedav85** [marko-js/marko#949] opened 2017-12-14 07:48 UTC
### Details
I use dynamic includes in my page and I load dynamicly components on client side and use the ```<include/>```-tag to render this components.

### Expected Behavior
The component should be rendered in the template.

### Actual Behavior
In marko version 4.6 everything is working well. With 4.7 no include is rendered. If I use the component tag directly it works.

### Your Environment
* marko 4.7.2
* lasso 3.0.0
* lasso-marko 2.4.0
* @ lasso/marko-taglib 1.0.8

### Steps to Reproduce
This is just an example.

Server side:
```javascript

let baseTemplate = require('./base-template');
let component = require('./component');

res.marko(baseTemplate, {
    template: component,
});
```

Client side:
```html
<!doctype html>
<html>
    <head>
        <lasso-head/>
    </head>
    <body>
        <if(data.template)>
            <include(data.template)/>

           <!-- The direct use of the component tag works -->
            <!-- <component/> -->
        </if>

        <lasso-body/>
    </body>
</html>
```

### Stack Trace
There are no errors.

**Comment by hedav85** [comment] 2017-12-14 08:03
It seems that the include is working. So I'll close this issue and investigate in more detailed tests what the concrete problem could be. It seems that the component is included but the component.js is not called. Looks like issue #946

**Comment by hedav85** [comment] 2017-12-14 12:16
I tested a bit more and the problem is that for the components which where included via the include-tag no client side JS is executed.

I also checked my browser.json. The js code is aviable at the client but not executed.

**Comment by ianvonholt** [comment] 2017-12-19 17:15
@hedav85 Could you please post your component code? I'll try to help you out with this one.

**Comment by DylanPiercey** [comment] 2017-12-21 20:11
@hedav85 is this a duplicate of https://github.com/marko-js/marko/issues/946?

**Comment by hedav85** [comment] 2018-01-03 11:59
@ianvonholt the component code is like:

```javascript
...
onCreate() {
    console.log("onCreate()");
}

onMount() {
    console.log("onMount()");
}
...
```

The onCreate is called on server side, but the onMount not on client side. 


@DylanPiercey I'm not sure if its really a duplicate or another problem. For me the problem is now focused on the include tag. If I include a component with this tag then the client side code is not executed. If I use the component tag directly the component code is executed on client side.

At the moment I try to reproduce the issue with a new sample, but I'm not able to reproduce this, so I think its related to some specifics of my project. With 4.6 everything is working fine.

**Comment by hedav85** [comment] 2018-01-03 12:18
After playing around with the include tag I could reproduce the problem (https://github.com/hedav85/marko-test).

The component tag and the include tag with a string literal works fine, bu the include tag with a variable generates the problem.

```html
<!-- not working! -->
<include(data.containerTemplate, { modules: data.modules })/>

<!-- working -->
<!-- <include('../container', { modules: data.modules })/> -->
<!-- <container modules=data.modules/> -->
```
The ```data.containerTemplate``` is required on server side and provided with the data object to the client.

In the example you will find this in the ```server.js```

**Comment by tigt** [comment] 2019-08-07 17:44
@hedav85: You might be able to fix the issue now that [`<include>` is deprecated in favor of dynamic tagnames](https://github.com/marko-js/marko/wiki/Deprecation:-include-tag):

```marko
<${data.containerTemplate} modules=data.modules />
```

**Comment by DylanPiercey** [comment] 2019-08-07 17:52
Looking at this again it would appear that `data.containerTemplate` is actually coming from the server side and probably not being processed into the browser bundle (which would be why no JS is executing).

With a file like

```marko
<include('../container', { modules: data.modules })/>
```

or

```marko
import Container from "../container";

<${Container} modules=data.modules/>
```

Both cause the `container` element to be shipped to the browser because it can be statically discovered.

If you want to pass in a template from the server side but still cause that to be shipped down you'll need to include it in a `browser.json` or if using webpack switch to one of the above.

A pattern I like is using a map if you've got a dynamic template from some server side input, eg

```marko
Import A from "./a.marko"
Import B from "./b.marko"
Import C from "./c.marko"

static const templates = { A, B, C };

<${templates[input.templateName]}/>
```

Which would be rendered like

```marko
<my-component templateName="A"/>
```

Going to close this one for now, feel free to leave another comment if this is not the case.

**Closed by DylanPiercey** 2019-08-07 17:52 UTC
Labels: needs more info, status:todo, type:unverified bug
