### ISSUE TITLE
Bug: Firefox doesn't display markojs.com graph propperly

### ISSUE THREAD

**Issue by tomByrer** [marko-js/marko#742] opened 2017-06-21 19:17 UTC
On the MarcoJS homepage, the graph won't show completely on Firefox Win10 (upto Nightly).
Missing are the non-MarcoJS bars, except for the 1 React bar where I hovered over with a mouse.

![marcojscom-bug-firefox](https://user-images.githubusercontent.com/1308419/27402434-3d919c3c-568c-11e7-8966-393928a58288.png)

**Comment by austinkelleher** [comment] 2017-06-22 17:24
Duplicate of https://github.com/marko-js/markojs-website/issues/15. Also I still cannot reproduce this issue. I've tried on the latest Firefox and latest Firefox nightly (56.0a1 (2017-06-21) (64-bit)). Please continue the conversation over at https://github.com/marko-js/markojs-website/issues/15.

**Closed by austinkelleher** 2017-06-22 17:24 UTC
