### ISSUE TITLE
[v4] `null` state properties not being watched

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#556] opened 2017-02-01 02:15 UTC
## Bug Report

Might be related to #516

```jsx

class {
  onInput(props) {
    // this.state = { error: '' } // Works
    this.state = { error: null } // Does not work
  }
  submit(e) {
    e.preventDefault()
    setTimeout(() => {
      console.log("Setting error")
      this.state.error = 'o no!'
    }, 100)
  }
}

<form on-submit('submit')>
  <p if(state.error)>
    Error: ${state.error}
  </p>
  <button type="submit">Sign In</button>
</form>
```

### Expected Behavior

On clicking the submit button, an error message should appear.

### Actual Behavior

Nothing appears. `this.state.error` is set correctly, but marko does not redraw.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: a3a179da (I couldn't wait 😄 )
* Environment name and version: Chrome 55
* Operating System and version: OS X
</details>

**Comment by philidem** [comment] 2017-02-01 02:50
I'll take a look at this tonight unless someone else is looking at it.

**Comment by philidem** [comment] 2017-02-01 18:47
I couldn't reproduce this issue in our test suite. Can you test your app again with `4.0.0-rc.11`?

Added test case:
https://github.com/marko-js/marko/commit/35517181e1e9602222b12bdfd7fb62767595c8d8

**Comment by mindeavor** [comment] 2017-02-01 18:52
It's still behaving the same on `rc.11`. Maybe the test is triggering a redraw programmatically?

**Comment by philidem** [comment] 2017-02-01 18:54
Thanks for checking agin.

It should be relying on the same implicit batching that happens in the web browser. I will try to run this same code in the browser to see if it works.

**Comment by philidem** [comment] 2017-02-01 19:53
@mindeavor I still wasn't able to reproduce this issue in a stand-alone project.

See https://github.com/philidem/marko-issue-556-state-error-null

Can you publish a repo that demonstrates the problem?

**Comment by mindeavor** [comment] 2017-02-01 20:55
So strange, it works in a standalone project for me too, but not my production app. I'm definitely using `rc.11`, and just tried `rm -rf node_modules/` to no avail. Something else must be happening...

**Comment by mlrawlings** [comment] 2017-02-01 22:02
@mindeavor can you share your compiled template output?

**Comment by mindeavor** [comment] 2017-02-01 22:59
Aha, I deleted my `yarn.lock` and everything works again. I wonder which package was not getting updated...

**Comment by patrick-steele-idem** [comment] 2017-02-01 23:00
Who knows, but everything related should be in the main `marko` package. Closing issue since no longer a problem.

**Closed by patrick-steele-idem** 2017-02-01 23:00 UTC
