### ISSUE TITLE
Creating a new project via cli fails

### ISSUE THREAD

**Issue by vaaski** [marko-js/marko#902] opened 2017-10-22 08:58 UTC
### Details

I decided to give Marko a try, installed it on my Microsoft Surface Pro 4 via `npm install -g marko-cli && npm install -g marko`

### Expected Behavior

I ran `marko create test` to create a sample project to try & play around with marko.

### Actual Behavior

It exited with lots of errors, with the first line being:
`× Command failed: cd C:\X\test && npm install` 

**[full console output](https://hastebin.com/averotalap)
[npm-debug.log](https://hastebin.com/egekihediv)**

### Possible Fix

I'm not sure, because I do not know the exact reason for the error.

### Your Environment

* Windows 10 1703 15063.674
* Node v6.11.0

### Steps to Reproduce

1. `marko create test`
2. i don't know it just failed, sorry 😢 
3. 
4. 

### Stack Trace

**[full console output](https://hastebin.com/averotalap)
[npm-debug.log](https://hastebin.com/egekihediv)**
</details>

If you need any more details, just tell me how to get them! :)

**Comment by patrick-steele-idem** [comment] 2017-10-24 17:35
It's working for me. It could be a Windows-specific issue, but it also looks like maybe you might have some connection issues to `github.com` based on your console output:

```
npm ERR! Cloning into bare repository 'C:\Users\x\AppData\Roaming\npm-cache\_git-remotes\git-github-com-mlrawlings-marko-magic-git-bc3da7ec'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Invalid argument
npm ERR! github.com[1: 192.30.253.113]: errno=Invalid argument
```

**Comment by DracotMolver** [comment] 2017-10-25 20:07
I was facing something similar. But not an error at all.
First. The cli created the folder structure perfecly. But, I just got the next message, which i think it was for the deprecated packages named below:

```bash
× Command failed: cd \marko\color-picker && npm install
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/mlrawlings/marko-magic.git
npm ERR!
npm ERR! fatal: read error: Invalid argument
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
````

**Comment by austinkelleher** [comment] 2017-10-26 11:02
@vaaski @DracotMolver Thanks for the report. I just tried this on a Windows VM and I couldn't reproduce it.

Could you please try it again? Perhaps it was just a connection issue the first time.

**Comment by DracotMolver** [comment] 2017-10-27 14:53
@austinkelleher Sorry for my late answer. In my case was a IP issue. I was trying Marko at work and I have some ports and IPs blocks (I think that's the only reason). I tried now at home and runs like a charm!. No problem following the color-picker-tutorial 👍

**Comment by austinkelleher** [comment] 2017-10-27 15:22
Thanks @DracotMolver! I think I will go ahead and close this out as it does not seem like an issue with marko-cli. Please feel free to reopen this issue or open another issue if this is indeed a problem.

**Closed by austinkelleher** 2017-10-27 15:22 UTC
Labels: status:todo, type:unverified-bug
