### ISSUE TITLE
Add support for Typescript

### ISSUE THREAD

**Issue by JarvisPrestidge** [marko-js/marko#858] opened 2017-09-25 11:03 UTC
### Description

Add Typescript type definition files, so Marko can be used by the ever growing Typescript community.

### Context
Useful for anyone who uses Typescript. Personally I love marko and want to use it in typed projects, but this is a barrier to doing so.

**Comment by austinkelleher** [comment] 2017-09-27 04:47
Thanks for opening this issue. This is a duplicate, which we are tracking here: https://github.com/marko-js/marko/issues/325

**Comment by JarvisPrestidge** [comment] 2017-09-27 10:21
Imo that issue has wider scope than what I was looking for, which was basically just types for the current marko package and not typed templates (which seems far more sophisticated issue).

**Comment by linweigao** [comment] 2017-12-13 18:57
+1

**Comment by suzel** [comment] 2018-01-21 08:40
👍

**Comment by trusktr** [comment] 2022-01-25 06:01
Indeed this does not seem a duplicate of #325

**Comment by DylanPiercey** [comment] 2022-01-25 13:46
I agree it's worth chunking up aspects of supporting typescript. Type definitions for the runtime is a good standalone ticket. Reopening this issue.

**Comment by fabrice8** [comment] 2022-08-21 15:00
Hi everyone. Please any update on this issue?

**Comment by fabrice8** [comment] 2022-08-21 15:00
Hi everyone. Please any update on this issue?

**Comment by tigt** [comment] 2022-08-31 18:54
@DylanPiercey has been working on TS support as his goal this quarter, and says:

> I'm (hopefully) 2–4 weeks away from completing typescript support.

But don’t be too disappointed if it takes a little longer than that!

**Comment by Alexandre-Fernandez** [comment] 2022-10-02 11:05
I was looking into marko for a new project but lack of typescript support is a deal break

**Comment by mohamedmoussa89** [comment] 2022-10-09 20:41
Looking forward to Typescript support ... no Typescript support is also a deal breaker for me.

**Comment by gioragutt** [comment] 2022-10-17 23:15
@DylanPiercey any updates on this? I would like to evaluate marko as a replacement for Pug and TS support would be superb.

**Comment by DylanPiercey** [comment] 2022-10-18 04:08
@gioragutt its a WIP at the moment. Hopefully EOM but we'll see.

**Comment by gioragutt** [comment] 2022-11-29 15:12
@DylanPiercey sorry to bother, any updates on this?

**Comment by tigt** [comment] 2022-11-30 18:41
Progress is slow but steady. Dylan’s been learning the hard way about the dark corners of TypeScript deep in the moloch so Marko authors can have automatic useful types and tab-completion, no matter what their `.marko` files get up to.

It turns out TypeScript has a lot of exciting restrictions around how far it’s willing to analyze, so usually the obvious approach doesn’t work, and neither does the next-obvious, and the proposed solution is a 200-comment GitHub issue that links to an RFC that’s been superseded by another RFC that’s hidden under a sign that says “Beware of the Leopard”, and… well, you get the idea.

We appreciate your patience, truly. Thanks for not giving up on this!

**Comment by gioragutt** [comment] 2022-11-30 18:43
@tigt god that sounds awful 😂 thanks for the reply, appreciate your work guys ❤️ good luck with it!

**Comment by fabrice8** [comment] 2022-11-30 18:52
> Progress is slow but steady. Dylan’s been learning the hard way about the dark corners of TypeScript deep in the moloch so Marko authors can have automatic useful types and tab-completion, no matter what their `.marko` files get up to.
> 
> It turns out TypeScript has a lot of exciting restrictions around how far it’s willing to analyze, so usually the obvious approach doesn’t work, and neither does the next-obvious, and the proposed solution is a 200-comment GitHub issue that links to an RFC that’s been superseded by another RFC that’s hidden under a sign that says “Beware of the Leopard”, and… well, you get the idea.
> 
> We appreciate your patience, truly. Thanks for not giving up on this!
> 
> 

Sound like a lot of critical work currently on one person's shoulder. Would you guys like to share a roadmap of the undergoing work so that instead of waiting, we can contribute someway somehow?

**Comment by tigt** [comment] 2022-11-30 19:41
📫 Todo | 🚧 In Progress | ☑️ Done
-----|-------------|-----
Validate types in CLI | Generate Type Definitions from .marko files | Upgrade language server to use parser upgrades related to TypeScript support.
 &nbsp; | Type the API exposed by Marko's runtime | Automatically strip types via @marko/compiler
  &nbsp; | Language Server Integration | Support TypeScript in Marko's syntax highlighting
  &nbsp; |  | Support TypeScript in Marko's parser
  &nbsp; | &nbsp; | Parser: add support for generics on Tag Parameters and Attribute Method Shorthand

**Comment by fabrice8** [comment] 2023-03-06 15:59
Marko Typescript is here. Thanks a lot

**Comment by gioragutt** [comment] 2023-03-08 15:04
@fabrice8 awesome! I've not been able to find any references to it in the official docs, when can that be expected?

**Comment by JarvisPrestidge** [comment] 2023-03-08 15:08
Still excited 6 years later! ❤️ Also curious where / when we can try this 👀

**Comment by fabrice8** [comment] 2023-03-08 15:12
Here: https://markojs.com/docs/typescript

**Closed** 2023-04-21 18:31 UTC
Labels: reason-closed:duplicate
