### ISSUE TITLE
Hot reloading not working with .html extension

### ISSUE THREAD

**Issue by steebchen** [marko-js/marko#555] opened 2017-01-30 16:39 UTC
### Description
I am using .html files only with marko html in it, but that prevents me from using marko's hot reload.

Lines:
- v4: https://github.com/marko-js/marko/blob/master/hot-reload/index.js#L133
- v3: https://github.com/marko-js/marko/blob/v3/hot-reload/index.js#L128 (and maybe L136 too)

### Context
I know that it's probably recommended to use .marko.html but I would like to stick with my implementation where I use `require('marko/node-require').install({ extension: '.html' })`.

### Possible Implementation
It would be cool if there would be an options object so I could simply use `{ extension: 'html' }` in the hot reload `.enable()` method too, or maybe even use the extension string from the install so that would work automatically.

### Open Questions
See above.

### Is this something you're interested in working on?
Yep, as long as it's clear how the implementation would work

**Comment by patrick-steele-idem** [comment] 2017-01-30 16:44
Hey @steebchen, this is a duplicate of [Issue #363 - Auto hot reload for any extensions provided when installing the Node.js require hook](https://github.com/marko-js/marko/issues/363). Would you have any interest in working on this? At the moment, that issue is lower priority, but we do plan to have it resolved by the time of the final v4 release.

**Comment by steebchen** [comment] 2017-01-31 22:31
Sorry for the duplicate, I should have searched for that. Will think of that, but I have no idea how marko works so I don't know whether I will fit into this. I have currently fixed it manually editing the file for now.

**Comment by mlrawlings** [comment] 2017-02-01 22:01
@austinkelleher has completed the work for this and we'll publish a new release candidate soon

**Closed by mlrawlings** 2017-02-01 22:01 UTC
