### ISSUE TITLE
Compiling Marko for Server with Webpack causes error on start

### ISSUE THREAD

**Issue by lostpebble** [marko-js/marko#769] opened 2017-07-19 14:18 UTC
### Context
I'm trying to compile marko through Webpack and marko-loader for my server deployment.

### Expected Behavior
Should just work once the server is started in my container, as it does in my local environment.

### Actual Behavior
This error is reported on server start:
```
Error: Cannot find module 'marko/dist/components\taglib\component-globals-tag'
2017-07-19T13:26:10.864205904Z     at Function.Module._resolveFilename (module.js:485:15)
2017-07-19T13:26:10.864217391Z     at Function.Module._load (module.js:437:25)
2017-07-19T13:26:10.864225248Z     at Module.require (module.js:513:17)
2017-07-19T13:26:10.864231796Z     at require (internal/module.js:11:18)
2017-07-19T13:26:10.864238583Z     at Object.<anonymous> (/app/webpack:/external "marko/dist/components\\taglib\\component-globals-tag":1:1)
2017-07-19T13:26:10.864250363Z     at __webpack_require__ (/app/webpack:/webpack/bootstrap 722f251100ad4225f558:19:1)
2017-07-19T13:26:10.864258152Z     at Object.<anonymous> (/app/webpack:/src/views/base.marko:10:1)
2017-07-19T13:26:10.864266134Z     at Object.<anonymous> (/app/index.js:6492:30)
2017-07-19T13:26:10.864273241Z     at __webpack_require__ (/app/webpack:/webpack/bootstrap 722f251100ad4225f558:19:1)
2017-07-19T13:26:10.864280387Z     at Object.__webpack_exports__.a (/app/webpack:/src/routes/page/PageRouter.ts:22:30)
```

### Possible Fix

I think it might have something to do with the path that is generated for the Marko module in the webpack bundle. As you can see there is a weird mix of forward and back slashes (this is when I `console.dir` the template on Windows in my compiled server):

![image](https://user-images.githubusercontent.com/1508863/28371326-f6720aa4-6c9c-11e7-9d0d-74f3fa82d912.png)

In the actual `index.js` bundle file, this is what the code looks like for the Marko part:
![image](https://user-images.githubusercontent.com/1508863/28371512-7ea93712-6c9d-11e7-9a5e-e4f410ca5d32.png)

*Note the double backslashes at the bottom there - could be the cause of the problem.

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
"marko": "4.4.18",
"marko-loader": "1.3.1",

* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js 8.1.4
* Operating System and version (desktop or mobile):

Webpack compile on Windows 10, server deployment is in a Linux container.

### Steps to Reproduce

1. 

In Webpack config for .marko files:
```
{
   test: /\.marko$/,
   loader: "marko-loader",
   query: { target: target === "node" ? "server" : "browser" },
},
```
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by austinkelleher** [comment] 2017-07-19 14:35
Hey @lostpebble thanks for reporting the issue. Can you provide a small project that reproduces the issue? It would be very helpful for debugging! Thanks!

**Comment by lostpebble** [comment] 2017-07-19 16:49
Can't put one together right now, but I can say I managed to solve it by not using `marko-loader`.

Instead I'm marking any files with `.marko` in them to be treated as an external (not to be processed / compiled by Webpack but rather leave the require as it stands):

```
externals: [/\.marko$/,]
```

And using `copy-webpack-plugin` to copy the actual template file into my bundle folder on compilation:

```
new CopyWebpackPlugin([
  { from: "src/views/base.marko" },
])
```

This allows me to use the other Marko server-side option of `require("marko/node-require")` before making the regular require for my template file (which is unchanged in the final bundle thanks to the `externals` option).

All in all, it appears that the `marko-loader` is doing something funky when compiling templates on Windows which is then not compatible on a different (Linux) system afterwards.

**Comment by DylanPiercey** [comment] 2017-08-19 17:31
@lostpebble I believe I ran into the same issue a couple days ago. It is because `component-globals-tag` is used in the server which is a marko component. Most likely your marko-loader is set to ignore node_modules.

In my case I switched my loader options for marko-loader to be:
```js
{
      test: /\.marko$/,
      exclude: /node_modules(?!\/marko)/,
      loader: 'marko-loader'
}
```

**Comment by DylanPiercey** [comment] 2017-12-21 19:36
@lostpebble going to close this issue for now but if the above did not resolve your issue feel free to comment back and ping me.

**Closed by DylanPiercey** 2017-12-21 19:36 UTC
