### ISSUE TITLE
Marko throws a series of (harmless?) errors in Electron.

### ISSUE THREAD

**Issue by defianceblack** [marko-js/marko#975] opened 2018-01-21 03:18 UTC
### Details
I'd put this in gitter.im a few days back:
 
Does anyone have an idea of what I do with:
Uncaught (in promise) TypeError: ComponentsContext.___initClientRendered is not a function ?

I used resultPromise.then((result) => result.appendTo(document.body)) inside renderer.js in Electron.

I should note that it does render the .marko file I required, but it does show that error and a chain of files; dom-insert, RenderResult and Components tracing back to my renderer.js

It's not detrimental (yet), but I want to understand the app I'm writing along the way

### Actual Behavior
Courtesy of @DylanPiercey on gitter.im:

that issue is actually because Marko uses the browser field in the package.json in some places throughout the codebase. I’m not entirely sure what the solution is for that at the moment however I will keep it in mind. If you don’t mind opening an issue that would be awesome. (Just note that your intention is to use marko templates in electron without precompiling).

### Your Environment
This occurred inside Electron. 
I was attempting to integrate Marko without the extra headache of bundling.
It was configured to use the vdom with a little help from Dylan a few days earlier

</details>

**Comment by DylanPiercey** [comment] 2018-08-29 03:54
Just noticed that this is kind of a duplicate of #704, lets track this over there.

**Closed by DylanPiercey** 2018-08-29 03:54 UTC
