### ISSUE TITLE
4.5.0 this.getEl() and this.getComponent()

### ISSUE THREAD

**Issue by 1N50MN14** [marko-js/marko#892] opened 2017-10-15 12:48 UTC
### Details
`this.getEl()` and `this.getComponent()` return `undefined` for elements with keys when using `<include>` within the included template. Example:

```marko
<div>
  <include('page.marko'), {}>
     <@body Hello World</@body>
  </include>
</div>
```
Any keyed elements or components inside `page.marko` will no longer be found by the component.

### Expected Behavior
Get a reference to the keyed element

### Actual Behavior
Receives `undefined`, this didn't happen prior to 4.5.0

### Your Environment
Android 8.0, Chrome latest.

</details>

**Comment by patrick-steele-idem** [comment] 2017-10-19 01:35
This change is an expected side effect of [Issue #854 - Make every .marko file a UI component](https://github.com/marko-js/marko/issues/854). Basically, we always intended for keyed elements to be scoped to the `.marko` file that it is in. The previous minor version of marko would automatically put keyed elements into the scope of the outer component if a `.marko` file did not have an explicit component associated with it. We cannot support the old (undocumented) behavior because it would introduce too many other unexpected behaviors.

Here's what you need to do to fix the problem:

You need to assign a key to the `<include>` so that you can get a reference to the included `page.marko` component. You then get get references to HTML elements in the scope of the page component. This is shown below:

```marko
class {
  onMount() {
    var deeplyNestedEl = this.getComponent('page').getEl('foo');
  }
}

<div>
  <include('page.marko'), {}) key="page">
     <@body Hello World</@body>
  </include>
</div>
```

In general, you don't want an outer component to directly reference HTML elements in the scope of a nested component since that will make your code more fragile. It is better if the nested page component explicitly exposes the HTML element by adding a method:

In `page.marko`

```marko
class {
  getFooEl() {
    return this.getEl('foo');
  }
}
```

And then in the outer component:

```js
var deeplyNestedEl = this.getComponent('page').getFooEl();
```

Hopefully this resolves your problem. I'm closing the issue, but please let us know if you have any concerns.

**Closed by patrick-steele-idem** 2017-10-19 01:35 UTC
Labels: type:unverified-bug
