### ISSUE TITLE
Default touch/wheel events to passive

### ISSUE THREAD

**Issue by tigt** [marko-js/marko#1404] opened 2019-08-22 15:46 UTC
## Description

This is an optimization that [Svelte](https://svelte.dev/) does to be fast by default, and it seems worth stealing:

> `passive` — improves scrolling performance on touch/wheel events (Svelte will add it automatically where it's safe to do so)
>
> <footer>—&hairsp;<a href="https://svelte.dev/tutorial/event-modifiers">Events / Event modifiers &bull; Svelte Tutorial</a></footer>

## Why

> Many times when you encounter scroll jank, the culprit is a touch event listener. Touch event listeners are often useful for tracking user interactions and creating custom scroll experiences, such as cancelling the scroll altogether when interacting with an embedded Google Map. Currently, browsers can't know if a touch event listener is going to cancel the scroll, so they always wait for the listener to finish before scrolling the page. Passive event listeners solve this problem by enabling you to set a flag in the `options` parameter of `addEventListener` indicating that the listener will never cancel the scroll. That information enables browsers to scroll the page immediately, rather than after the listener has finished.
>
> <footer>—&hairsp;<a href="https://developers.google.com/web/updates/2016/06/passive-event-listeners">Improving Scroll Performance with Passive Event Listeners</a></footer>

## Possible Implementation & Open Questions

* [sveltejs/svelte/src/compiler/compile/nodes/Element.ts#L70](https://github.com/sveltejs/svelte/blob/3e450eeee8c0417e7ac92844f533564004567746/src/compiler/compile/nodes/Element.ts#L70)
* [sveltejs/svelte/src/compiler/compile/nodes/EventHandler.ts#L27](https://github.com/sveltejs/svelte/blob/73a745b8d10da9c80d1c7b8d1771e37c058f25dc/src/compiler/compile/nodes/EventHandler.ts#L27)

## Is this something you're interested in working on?

Yes

**Comment by x4080** [comment] 2020-09-04 02:46
Hi, is this what lighthouse warning about ? And is it already implemented yet ?


Thanks

**Comment by tigt** [comment] 2020-09-05 18:06
Yes, I think this is one and the same.

[Does not use passive listeners to improve scrolling performance](https://web.dev/uses-passive-event-listeners/):

> Touch and wheel event listeners are useful for tracking user interactions and creating custom scrolling experiences, but they can also delay page scrolling. Currently, browsers can't know if an event listener will prevent scrolling, so they always wait for the listener to finish executing before scrolling the page. Passive event listeners solve this problem by letting you indicate that an event listener will never prevent scrolling.

Unfortunately, no, it is not implemented yet, nor the functionality to manually set such listeners to passive (#1408). You can remove the warning by bypassing the `onEvent=` attribute name shortcuts and instead getting a ref and attaching event listeners the old-fashioned way.

**Comment by x4080** [comment] 2020-09-05 20:15
@tigt Thanks

**Comment by DylanPiercey** [comment] 2022-06-10 03:11
I think this is largely a duplicate of https://github.com/marko-js/marko/issues/1408

**Closed by DylanPiercey** 2022-06-10 03:11 UTC
